// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview A financial trend identification AI agent.
 *
 * - identifyFinancialTrends - A function that handles the financial trend identification process.
 * - IdentifyFinancialTrendsInput - The input type for the identifyFinancialTrends function.
 * - IdentifyFinancialTrendsOutput - The return type for the identifyFinancialTrends function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const IdentifyFinancialTrendsInputSchema = z.object({
  financialData: z.string().describe('The church financial data in JSON format. Include the last 12 months of income and expenses.'),
});
export type IdentifyFinancialTrendsInput = z.infer<typeof IdentifyFinancialTrendsInputSchema>;

const IdentifyFinancialTrendsOutputSchema = z.object({
  trends: z.string().describe('Key trends in giving patterns over the past year.'),
  insights: z.string().describe('Insights for financial planning based on the identified trends.'),
  recommendations: z.string().describe('Recommendations for budgeting and resource allocation.'),
});
export type IdentifyFinancialTrendsOutput = z.infer<typeof IdentifyFinancialTrendsOutputSchema>;

export async function identifyFinancialTrends(input: IdentifyFinancialTrendsInput): Promise<IdentifyFinancialTrendsOutput> {
  return identifyFinancialTrendsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'identifyFinancialTrendsPrompt',
  input: {schema: IdentifyFinancialTrendsInputSchema},
  output: {schema: IdentifyFinancialTrendsOutputSchema},
  prompt: `You are a financial analyst specializing in identifying trends and insights from financial data.

You will use the provided financial data to identify key trends in giving patterns over the past year, provide insights for financial planning, and offer recommendations for budgeting and resource allocation.

Financial Data: {{{financialData}}}
`,
});

const identifyFinancialTrendsFlow = ai.defineFlow(
  {
    name: 'identifyFinancialTrendsFlow',
    inputSchema: IdentifyFinancialTrendsInputSchema,
    outputSchema: IdentifyFinancialTrendsOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
